- rules.js
If you import libdef for flow you will get a warning of duplicate import, the rule `no-duplicate-imports` does not supports flow but `import/no-duplicates` does.
Failing code which is correct as example:
```javascript
import { action, observable } from 'mobx';
import type { ObservableArray } from 'mobx';
```
Original issue on eslint open here https://github.com/babel/eslint-plugin-babel/issues/59
> fix(eslint): disable `no-duplicate-imports`

- rules.js
- sample-project/src/connect.js
eslint & prettier were not enforcing the same line length, now they have the same line limit to 120 characters.
> fix(prettier): use same `printWidth` as `max-len`

- .eslintrc.js
- .travis.yml
- README.md
- base.js
- flowtype.js
- package.json
- react.js
- rules/base.js
- rules/react.js
- sample-project/.eslintignore
- sample-project/.eslintrc.js
- sample-project/package.json
- scripts/release.sh
- scripts/test.sh
- vue.js
- yarn.lock
There are now individual configurations for each type of project.
The README has been reformatted to ease setup.
I removed direct dependencies and we now enforce the
user to install what he needs.
The default setup is always: ESLint + prettier
Then some custom plugins are used.
The way the various config files are written may be a bit weird but I am
unsure how multiple extends works (how the order is done) and we need to always have prettier
last, so it might sometime be a bit redundant having prettier
everywhere, seems to be working still.
I'll publish this on the @next tag so you can try it:
```sh
yarn add eslint-config-algolia@next --dev
```
Then follow the README
> feat(confs): Base, React, Flowtype & Vue confs

- sample-project/package.json
`":lib"` does not exist, you probably intended `":library"`. However I have deprecated that now in favour of `"config:*"` presets. As you have pinned version numbers in all dependency types here, the most appropriate is `"config:base"`.
> chore: fix renovate preset

- sample-project/.eslintrc.js
- sample-project/package.json
- sample-project/yarn.lock
This makes sure we don't need to import relatively in the config, and are closer to a real setup. The linting still errors if there are errors in the setup
> chore: import relatively in test file

- rules/base.js
We discuss a bit about that in routing PR of InstantSearch (I didn't find where, the PR is a bit large).
Enable the `curly` rule to his default value which is [`all`](https://eslint.org/docs/rules/curly#all).
> feat: enable curly rules

- rules/base.js
**Summary**
This rule allow to easily omit values from an object.
> https://eslint.org/docs/rules/no-unused-vars#ignorerestsiblings
```js
const sample = {
value: "hello",
omit: "world"
};
const render = ({ omit, ...rest }) => {
console.log(rest); // { value: 'hello' }
};
```
> feat(base): allow unused var with rest

- rules/base.js
- sample-project/index.js
- sample-project/src/Provider.js
- sample-project/src/connect.js
As reported by @samouss we lack consistency in projects for extensions when importing files. Some projects suffers more from it than others (eg. instantsearch.js).
This rules forces to remove the extensions when importing js files.
Those were valide before:
```js
import lib from './lib.js';
import lib2 from './otherLib';
```
Now:
```js
import lib from './lib.js'; // 🙅‍♂️
import lib2 from './otherLib'; //  ✅
```
Related to https://github.com/algolia/instantsearch.js/pull/3022
> feat(import): enforce no extensions for js files

- rules/base.js
Invert the actual condition - Ignore packages by default then disable it for JS.
> fix(extensions): ignorePackages by default + JS override

- rules/typescript.js
As discussed in the team,  while being useful to add explicitness and avoid some implicit `any`, the `@typescript-eslint/explicit-function-return-type` rule (added in https://github.com/algolia/eslint-config-algolia/pull/106) also adds some unwanted verbosity, can break inferred types if misused and the more we type our code the less it become useful (less implicit `any` to catch).
For these reasons we decided to disable it.
> feat(rules): disable @typescript-eslint/explicit-function-return-type

- rules/typescript.js
Keeping an unused variable in a function signature is sometimes useful to know what data we're dealing with. A common pattern is to prefix this variable with `_` to make it explicit that it's not used but it's usable. This pattern is used in the InstantSearch codebases.
This rule is already used in the [InstantSearch.js ESLint configuration](https://github.com/algolia/instantsearch.js/blob/b6ee2596d353ea692d91929759bc2b2fe34945c7/.eslintrc.js#L9-L12).
```ts
function example(start: number): number[] {
const values = ['a', 'b', 'c'];
return values.map((_, index) => start + index);
}
```
> feat(typescript): allow unused vars starting with underscores

- rules/typescript.js
I based my changes on https://github.com/xojs/eslint-config-xo-typescript/commit/1053f6b449440985a7f07d4dfc237440c52a3503
and the changelog: https://github.com/typescript-eslint/typescript-eslint/blob/master/CHANGELOG.md#200-2019-08-13
fixes #113
This doesn't seem to be tested anywhere, so :fingers_crossed: haha
BREAKING CHANGE: /typescript requires typescript-eslint v2 now
> feat(ts): compat for typescript-eslint 2

- rules/typescript.js
We accept only generic type names starting with "T" but sometimes, accepting "K" also makes sense. This is the case when using the TypeScript keyword `keyof`:
```ts
type StateToWidgets = {
[KParameter in keyof IndexUiState]: Array<Widget['$$type']>;
};
```
- `keyof` feature: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-1.html#example
- Original need: https://github.com/algolia/instantsearch.js/pull/4140#discussion_r327328222
> feat(typescript): allow generic names starting with "K"

- README.md
- react.js
- rules/react.js
- sample-project/package.json
- sample-project/src/Component.js
- sample-project/yarn.lock
This adds the [ESLint plugin for React hooks](https://reactjs.org/docs/hooks-rules.html#eslint-plugin) to enforce good hooks usage.
This is a breaking change because the peer dependency `eslint-plugin-react-hooks` is now required.
> feat(react): add hooks rules

- README.md
- base.js
- package.json
- rules/base.js
- sample-project/package.json
- sample-project/yarn.lock
- yarn.lock
Fixes #112
This change adds the [eslint-plugin-eslint-comments](https://mysticatea.github.io/eslint-plugin-eslint-comments/) plugin to the `base` configuration.
All rules from the [Best Practices](https://mysticatea.github.io/eslint-plugin-eslint-comments/rules/#best-practices) section are enabled.
This is a **breaking change** since the configuration requires a new peerDependency.
> feat: add eslint-plugin-eslint-comments plugin

- base.js
- rules/base.js
- rules/typescript.js
This PR update the TypeScript rules to support [`@typescript-eslint/eslint-plugin`](https://github.com/typescript-eslint/typescript-eslint) 3.x
You can read the full changelog for 3.0.0 here: https://github.com/typescript-eslint/typescript-eslint/releases/tag/v3.0.0
This is a breaking change since this config will now require `@typescript-eslint/eslint-plugin` 3.x and will not work anymore with 1.x or 2.x
> feat(typescript): add support for @typescript-eslint/eslint-plugin 3.x

- packages/eslint-config-algolia/rules/typescript.js
The config fails with recent versions of `typescript-eslint` with the following error (visible here: https://github.com/algolia/renderscript/pull/693):
```
Error: .eslintrc.js » eslint-config-algolia/typescript » ./rules/typescript.js:
Configuration for rule "@typescript-eslint/member-ordering" is invalid:
Value ["public-static-field","protected-static-field","private-static-field","public-instance-field","protected-instance-field","private-instance-field","public-abstract-field","protected-abstract-field","private-abstract-field","public-field","protected-field","private-field","static-field","instance-field","abstract-field","field","constructor","public-static-method","protected-static-method","private-static-method","public-instance-method","protected-instance-method","private-instance …
```
> fix: remove private-abstract-* options from member-ordering

- .gitignore
- packages/eslint-config-algolia/package.json
- packages/eslint-config-algolia/rules/base.js
- yarn.lock
`jsdoc/newline-after-description` was removed in `eslint-plugin-jsdoc` v42: https://github.com/gajus/eslint-plugin-jsdoc/compare/v41.1.2...v42.0.0
It's replaced by [`jsdoc/tag-lines`](https://github.com/gajus/eslint-plugin-jsdoc/blob/main/docs/rules/tag-lines.md#readme)
To match the old behaviour, it needs to be configured with:
- `'any'` to say that we don't enforce anything regarding if there are blank lines between tags or not
- `startLines: 1` to enforce having a blank line between the description and the tags (this is what was enforced by `jsdoc/newline-after-description`)
- `endLines: null` to not enforce anything after the tags
(spotted because it makes the linting fail in Renderscript: https://github.com/algolia/renderscript/pull/797)
- `yarn install`
- `cd …
> feat: plugin jsdoc v43

- scripts/release.sh
- yarn.lock
The release script wasn't updating the `yarn.lock` after bumping the version, that's why CI is failing after releasing: https://app.circleci.com/pipelines/github/algolia/eslint-config-algolia/1049/workflows/1eeeda3e-db30-48ed-9ced-1819a54a1d62/jobs/1046
> fix: release script should update yarn.lock

- README.md
- packages/eslint-config-algolia/.eslintrc.js
- packages/eslint-config-algolia/eslint.config.js
- packages/eslint-config-algolia/flat/base.js
- packages/eslint-config-algolia/flat/jest.js
- packages/eslint-config-algolia/flat/react.js
- packages/eslint-config-algolia/flat/typescript.js
- packages/eslint-config-algolia/flat/vue.js
- packages/eslint-config-algolia/package.json
- packages/test/eslint.config.js
- packages/test/package.json
- packages/test/src/connect.jsx
- packages/test/tsconfig.json
- scripts/test.sh
- yarn.lock
Introduce flat configs ([blog](https://eslint.org/blog/2022/08/new-config-system-part-2/), [doc](https://eslint.org/docs/latest/use/configure/configuration-files)), required to migrate to ESLint 9 (#342).
Migration guide: https://eslint.org/docs/latest/use/configure/migration-guide
To keep our config compatible with legacy versions, I've created new configs in a separate `flat/` directory.
You can see the new usage in the updated README or in the `packages/test/eslint.config.js` files:
```js
// eslint.config.js
const algolia = require('eslint-config-algolia/flat/base');
module.exports = [
...algolia,
];
```
I've tried to keep changes minimal, configs in the `flat/` dir are meant to be a simple port.
A lot of plugins already expose ways to work with flat configs, I simply followed their …
> feat: introduce flat config

- packages/eslint-config-algolia/flat/jest.js
- packages/test/eslint.config.js
- packages/test/src/connect.jsx
- packages/test/src/simple.test.js
- yarn.lock
I figured out that Jest flat configs are containing the following:
```
{
plugins: { jest: plugin },
languageOptions: { globals },
rules,
}
```
https://github.com/jest-community/eslint-plugin-jest/blob/98087f9bb27082f9fbda59a56c65536fb9d8a0dc/src/index.ts#L95
So spreading the `style` config in the same config object than the `recommended` config was actually overriding it.
I've added a simple test file with some disabled rules, and set `reportUnusedDisableDirectives` to error so it will report if those rules are not included anymore.
> fix: correctly import jest flat configs
